### ISSUE TITLE
Workflow help

### ISSUE THREAD

**Issue by ghost** [shekhar-shubhendu/supply-chain#7]
Can someone help with the workflow. As in, in which order am I supposed to place the orders.

**Comment by Anupamskd7** [comment]
Got this error: Please help

root@anupam-VirtualBox:/home/anupam/supply-chain# truffle compile pure

Compiling your contracts...
===========================
Error: CompileError: Error parsing /home/anupam/supply-chain/contracts/OrderRegistry.sol: ParsedContract.sol:77:53: ParserError: The state mutability modifier "constant" was removed in version 0.5.0. Use "view" or "pure" instead.
  function getReport(string orderno, uint category) constant returns(string) {
                                                    ^------^
Compilation failed. See above.
    at async.whilst.error (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-compile/profiler.js:366:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-compile/~/async/dist/async.js:969:1
    at next (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-compile/~/async/dist/async.js:5222:1)
    at Promise.all.then.results (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-compile/profiler.js:348:1)
    at <anonymous>
Truffle v5.0.9 (core: 5.0.9)
Node v8.10.0
root@anupam-VirtualBox:/home/anupam/supply-chain#

**Comment by shekhar-shubhendu** [comment]
Flow would be something like this:

retailer --> distributor --> manufacturer --> supplier
